"""describe change

Revision ID: 55e3accafca3
Revises: 20260619_0004
Create Date: 2026-09-01 15:14:15.779787
"""
from alembic import op
import sqlalchemy as sa


revision = '55e3accafca3'
down_revision = '20260619_0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
