"""add status_reason to bookings

Revision ID: 89e04b0aba1f
Revises: d2b96da3a3de
Create Date: 2026-09-01 17:28:19.729424
"""
from alembic import op
import sqlalchemy as sa


revision = '89e04b0aba1f'
down_revision = 'd2b96da3a3de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('status_reason', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'status_reason')
    # ### end Alembic commands ###
